version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://user:pass@db:5432/auth_db
      - AUTH0_DOMAIN=mock-auth0.com
      - AUTH0_CLIENT_ID=mock-client-id
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"

  locust-master:
    image: locustio/locust:latest
    ports:
      - "8089:8089"
      - "5557:5557"
    volumes:
      - ./load_tests:/mnt/locust
    command: -f /mnt/locust/locustfiles/auth_load_test.py --master -H http://auth-service:8000
    depends_on:
      - auth-service
    environment:
      - LOCUST_USERS=1000
      - LOCUST_SPAWN_RATE=100
      - LOCUST_RUN_TIME=10m

  locust-worker:
    image: locustio/locust:latest
    volumes:
      - ./load_tests:/mnt/locust
    command: -f /mnt/locust/locustfiles/auth_load_test.py --worker --master-host=locust-master
    depends_on:
      - locust-master
    scale: 4  # Scale to 4 workers for heavy load testing

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./load_tests/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data: