global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    
  - job_name: 'locust'
    static_configs:
      - targets: ['locust-master:8089']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']